version: 2.1

jobs:
  validate-changes:
    docker:
      # pre-commit package is included since 20.10
      - image: ubuntu:22.04
    steps:
      - run:
          name: check git version
          command: |
            apt update && apt install -y shellcheck pre-commit git
            pre-commit run --all-files
      - checkout
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate-changes
